import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

vecsumratios = np.load("/home/smagedov/local/src/sjet-local/GaussianMultijet/npyarrays/vecsumratios.npy")
ratios = np.load("/home/smagedov/local/src/sjet-local/GaussianMultijet/npyarrays/ratios.npy")
dists = np.load("/home/smagedov/local/src/sjet-local/GaussianMultijet/npyarrays/dists.npy")
deltar = np.load("/home/smagedov/local/src/sjet-local/GaussianMultijet/npyarrays/deltar.npy")
clusdis = np.load("/home/smagedov/local/src/sjet-local/GaussianMultijet/npyarrays/clusdis.npy")
masses = np.load("/home/smagedov/local/src/sjet-local/GaussianMultijet/npyarrays/masses.npy")

mask = (ratios >= 0.3) & (ratios <= 1.0)
plt.hist2d(dists[mask], ratios[mask], cmin=1, bins=50)
plt.colorbar(label='Count in bin')
plt.xlabel("Distance")
plt.ylabel("Scalar Sum PT Ratio")
plt.title("Scalar Sum PT Ratio vs Distance")
plt.savefig("/home/smagedov/local/src/sjet-local/GaussianMultijet/plots/clusqual_scalarsumptratio.png")
plt.show()

mask = (vecsumratios >= 0.3) & (vecsumratios <= 1.0)
plt.hist2d(dists[mask], vecsumratios[mask], cmin=1, bins=50)
plt.colorbar(label='Count in bin')
plt.xlabel("Distance")
plt.ylabel("Vec Sum PT Ratio")
plt.title("Vec Sum PT Ratio vs Distance")
plt.savefig("/home/smagedov/local/src/sjet-local/GaussianMultijet/plots/clusqual_vecsumptratio.png")
plt.show()

plt.hist2d(dists, deltar, cmin=1, bins=50)
plt.colorbar(label='Count in bin')
plt.xlabel("Distance")
plt.ylabel("Delta R")
plt.title("Delta R vs Distance")
plt.savefig("/home/smagedov/local/src/sjet-local/GaussianMultijet/plots/clusqual_deltar.png")
plt.show()

plt.hist2d(dists, clusdis, cmin=1, bins=50)
plt.colorbar(label='Count in bin')
plt.xlabel("Distance")
plt.ylabel("Delta R")
plt.title("Delta R (PT weight) vs Distance")
plt.savefig("/home/smagedov/local/src/sjet-local/GaussianMultijet/plots/clusqual_deltarptratio.png")
plt.show()

mask = (masses >= 0.0) & (masses <= 300.0)
plt.hist2d(dists[mask], masses[mask], cmin=1, bins=50)
plt.colorbar(label='Count in bin')
plt.xlabel("Distance")
plt.ylabel("Mass")
plt.title("Mass vs Distance")
plt.savefig("/home/smagedov/local/src/sjet-local/GaussianMultijet/plots/clusqual_mass.png")
plt.show()
